### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by andrewmckinnon2** [andrewmckinnon2/Rate-Your-Dorms#4]
- [x] Link clicks from search bar to actual pages

- [x] Hide dropdown from search bar 

- [x] Clear Andrew's html so to not appear when page initially loads
